version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 99
    directory: /
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/Toronto
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      - dependency-name: eslint
        versions: '>= 10'
    groups:
      eslint:
        dependency-type: development
        patterns:
          - eslint
          - eslint-*
          - '@eslint/*'
          - '@eslint-community/*'
      spdx:
        dependency-type: production
        patterns:
          - spdx-*
