documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package-lock.json
github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*.yml
javascript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.js'
      - bin/d2l-license-checker
