env:
language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - set -e
  - npm run lint
  - npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: npm publish --verbose
  on:
    branch: master
    tags: true
