language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "node"
script:
  - set -e
  - npm run lint
  - npm run test
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
    # 57c4......d343
    secure: "bc6j6Afp29Zx4HaNUo+tJ6XEG4yuEK4VW8PGJ/gN4Gz4pNjnLqIN4/8QfEOtXwT3QL4qgSgBvqALOuUXJMMVHIiejO61es/FJcN6qZNlqfJ/cB2En6/4KL/JXLKOWrDks23jmqf3WygIRwO52XgTlwAt8ArIfckmN3w55A7sZ5SGVMp539faXxKy7ae1kzAb9031RJug5jeqawYBYaMd7E/FmRbRVcWE4sDSZ/t7TdpmtL7zR0mRwCk7w1mXC1SiyRAjjH/s3JBj8oyASd17SiCTlm8pAvS99FoybuwVSMGBk2yrGfKQ6tAQ5q48IS1We8nsCkzMqLVgm7ur4Vbes9FLey5rWsOHYTpP/Y5+aOEYOnbRCgDzHBxI7HS6QRgynEXnHVvEy+3wjMXdnYR+plner3xp9r57lGGRZpTyVZkEdS0F44gyu33mr1cvaZp8/ZkVwDdhNzNTpiIBwEHJKLuCEDD9Kqyj2p49/jShSFBSTwCqoL3qC8py8jmSXapIZVSAH/AL6XctekeRwraygDLsMsFbtPgep5OcChAXt7H3Eh8fksCqmaHL6howmW72W0OAGiui+X5ADHcLVs0Smk6WYZvbHwkBYVSjlzR/4GrJKIgDRd2JFVvKFWqv9GWAV9pAj/dCAMEUOuvP3asbp+iGAX14fF1MktDPqGFBuoU="
  on:
    branch: master
    tags: true
