env:
  global:
    - ARTIFACTORY_REGISTRY=https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/npm-local
language: node_js
node_js:
  - "6"
install:
  - curl -ks -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS "${ARTIFACTORY_REGISTRY}/auth/d2l" -o .npmrc
  - npm config set @d2l:registry $ARTIFACTORY_REGISTRY
  - npm install
script:
  - set -e
  - npm run lint
  - npm run test
deploy:
  provider: script
  script: npm publish --verbose --registry $ARTIFACTORY_REGISTRY
  on:
    branch: master
    tags: true
notifications:
  slack:
    rooms:
      - d2l:8ahxQtnW0ygxQ8KQUmllSkLF#aurora-build
    on_pull_requests: false
    on_success: change
    on_failure: always
