language: node_js
node_js:
  - "8.10"
  - "10"
script:
  - set -e
  - npm run lint
  - npm run test
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
    # 57c4......d343
    secure: "LNAzS24n4D+NdzkRyvGemkOjBqoJCewfYI1y11geZ13ug6Uk0dpkdad0RpLy9xAgiT7N2QJrO5tXmK1XdqquGQd6G27qkM9iMW/+n0hTmgrxyZM8imPAVri3pWakjEGKfZFDC6Wd4s61TCWZXKhTnh+X7p77fcYZD/3nXHFlx3GfSENrmyB7w2bieFdSEdhuOjHzO7MW8yG5sp53GPYEh86FY0hn9tPoNCLm10rU0J90TmPJJ/WYXC3Q+PyQvXmABV3o8FUq/rsYvCXuFRg1KWaU1IAOF9kicHP0zKENojbRJl13cl27Qojp2JsnCqQeG+Q8MGHyNnvFJzSwVskFk7qZs46sXEyCteIQPb2MpOaJ8miZl2yN4nrAAP9HTe9jSu/5Rkh16Z+zbeVy9j3y6xtuNcj1gG0Nk/A5UhLL2OXAkr39M5u/EpfgzEwkGTe0eZj4PuJJBSSlo4U0QD8sqRVqFUUpm9+LnqMzTWTMvEAksdyV1TNDP4s/8sJisD2ivhaNnf9mzllvOH6wBh75AnwCCOsCqNZdncAW68PnLN82xsXZQaziEGlgdv6cocrkvTI2wWbHZ+z8M/uhDaG002iX3B/9SleluyQwUyz+Dyd0H1rb92zRapO8lBY0RXqKYzalVlsL0FCMlUStucyoVFbVHeXYnhjpcDnbtb9dz/k="
  on:
    branch: master
    tags: true
