env:
  global:
    - ARTIFACTORY_REGISTRY=https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/npm-local
language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - set -e
  - npm run lint
  - npm run test
deploy:
  provider: script
  script:
    - curl -ksf -u"$ARTIFACTORY_USER:$ARTIFACTORY_PASS" "${ARTIFACTORY_REGISTRY}/auth/d2l" -o .npmrc
    - npm publish --verbose --registry $ARTIFACTORY_REGISTRY
  on:
    branch: master
    tags: true
