name: Lint and Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: npm install
        run: npm ci --only=prod
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
