name: Update Dependencies
on:
  schedule:
    # Runs monthly
    - cron:  '0 13 1 * *'
  workflow_dispatch:
jobs:
  update-deps:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@neverendingqs/gh-action-node-update-deps
        env:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
