name: D2L License Checker CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        node: ['12', '14', '16', '18', '20']
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    name: Release
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 14 # lowest version semantic release supports
      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.D2L_RELEASE_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
