name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  determine-node-versions:
    name: Determine Node Versions
    runs-on: ubuntu-latest
    outputs:
      node-versions: ${{steps.gnv.outputs.node-versions}}
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Generate node versions
        id: gnv
        run: |
          NVMRC_VER=$(cat .nvmrc)
          VER=${NVMRC_VER%%.*}
          VER_BELOW=$((VER-2))
          VER_ABOVE=$((VER+2))
          echo "node-versions=[\"$VER_BELOW\",\"$VER\",\"$VER_ABOVE\"]" >> $GITHUB_OUTPUT
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: determine-node-versions
    strategy:
      fail-fast: false
      matrix:
        node: ${{fromJson(needs.determine-node-versions.outputs.node-versions)}}
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    name: Release
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.D2L_RELEASE_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
